ARG PHP_VERSION_TAG
FROM php:${PHP_VERSION_TAG}

RUN apt-get update && apt-get upgrade -y \
    git \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpq-dev \
    libmagickwand-dev \
    libmcrypt-dev \
    libpng-dev \
    libmemcached-dev \
    libssl-dev \
    libssl-doc \
    zlib1g-dev \
    libicu-dev \
    libxml2-dev \
    g++ \
    && docker-php-ext-install \
        bz2 \
        iconv \
        mbstring \
        mcrypt \
        mysqli \
        opcache \
        pgsql \
        pdo_mysql \
        pdo_pgsql \
        soap \
        zip \
    && docker-php-ext-configure gd \
        --with-freetype-dir=/usr/include/ \
        --with-jpeg-dir=/usr/include/ \
        --with-png-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-install exif \
    && docker-php-ext-configure intl  \
    && docker-php-ext-install intl \
    && pecl install mongodb && docker-php-ext-enable mongodb \
    && echo 'no' | pecl install redis && docker-php-ext-enable redis \
    && echo 'yes' | pecl install imagick && docker-php-ext-enable imagick

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/bin/composer \
    && chmod a+x /usr/bin/composer

RUN cd /var/www/ \
    && composer create-project yiisoft/yii2-app-basic html

RUN sed -i "s/mysql:host=localhost;dbname=${MYSQL_DATABASE}/mysql:host=mariadb;dbname=${MYSQL_DATABASE}/" html/config/db.php \
    && sed -i "s/'username' => 'root'/'username' => '${MYSQL_USER}'/" html/config/db.php \
    && sed -i "s/'password' => ''/'password' => '${MYSQL_PASSWORD}'/" html/config/db.php