version: '2'

services:
    nginx:
        image: nginx:${NGINX_VERSION_TAG}
        volumes:
            - "./conf/nginx:/etc/nginx/conf.d"
            - "./log/nginx:/var/log/nginx"
            - "./app:/var/www/html"
        ports:
            - ${DYDE_NGINX_EXPOSE_PORT}:80
        restart: always
        # depends_on:
        #     - php
    mariadb:
        image: mariadb:${MYSQL_VERSION_TAG}
        restart: always
        ports:
            - ${DYDE_MYSQL_EXPOSE_PORT}:3306
        volumes:
            - "./conf/mysql:/etc/mysql/conf.d"
            - "./data/mysql:/var/lib/mysql"
            - "./log/mysql:/var/log/mysql"
    redis:
        image: redis:${REDIS_VERSION_TAG}
        restart: always
        volumes:
            - "./data/redis/:/data"
    php:
        build:
            context: ./conf/php
            dockerfile: Dockerfile-php
            args:
                - PHP_VERSION_TAG=${PHP_VERSION_TAG}
        restart: always
        volumes:
            - "./conf/php/php.ini:/usr/local/etc/php/php.ini"
            - "./app:/var/www/html"
        depends_on:
            - mariadb
            - redis